apiVersion: v1
kind: ReplicationController
metadata:
    name: rcweb1

spec:
   replicas: 3
   selector: 
      dc: IN

   template:
      metadata:
           name: mypod1
           labels:
               env: dev
               dc: IN

      spec:
         containers:
         - name: "mycontainer1"
           image: "vimal13/apache-webserver-php"
            